"""
Atlas Base Strategy Classes
================================
Abstract base class and Signal dataclass for all trading strategies.

Usage:
    from strategies.base import BaseStrategy, Signal
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy.

    Attributes:
        ticker: Ticker symbol (e.g., 'BHP.AX', 'AAPL').
        strategy: Name of the strategy that generated this signal.
        direction: Trade direction ('long' only for v1).
        entry_price: Planned entry price per share.
        stop_price: Stop-loss price per share.
        take_profit: Take-profit price (None if trailing stop only).
        position_size: Number of shares to buy.
        position_value: Total cost of position in local currency.
        risk_amount: Total dollar risk if stop is hit.
        confidence: Signal confidence score (0.0 to 1.0).
        rationale: Plain English explanation of why this signal was generated.
        features: Dict of key indicators that triggered the signal.
        market_id: Market this signal belongs to (e.g., 'asx', 'sp500').
        timestamp: When the signal was generated.
    """
    ticker: str
    strategy: str
    direction: str  # 'long' only for v1
    entry_price: float
    stop_price: float
    take_profit: Optional[float]
    position_size: int
    position_value: float
    risk_amount: float
    confidence: float
    rationale: str
    features: Dict[str, Any] = field(default_factory=dict)
    market_id: str = ""
    sector: str = "Unknown"
    timestamp: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate signal fields after initialization."""
        if self.direction != "long":
            raise ValueError(f"Only 'long' direction supported in v1, got '{self.direction}'")
        if self.confidence < 0.0 or self.confidence > 1.0:
            raise ValueError(f"Confidence must be in [0, 1], got {self.confidence}")
        if self.stop_price >= self.entry_price:
            raise ValueError(
                f"Stop price ({self.stop_price}) must be below entry price "
                f"({self.entry_price}) for long positions"
            )
        if self.take_profit is not None and self.take_profit <= self.entry_price:
            raise ValueError(
                f"Take profit ({self.take_profit}) must be above entry price "
                f"({self.entry_price}) for long positions"
            )
        if self.position_size <= 0:
            raise ValueError(f"Position size must be positive, got {self.position_size}")

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to a plain dictionary for serialization."""
        return {
            "ticker": self.ticker,
            "strategy": self.strategy,
            "direction": self.direction,
            "entry_price": self.entry_price,
            "stop_price": self.stop_price,
            "take_profit": self.take_profit,
            "position_size": self.position_size,
            "position_value": self.position_value,
            "risk_amount": self.risk_amount,
            "confidence": self.confidence,
            "rationale": self.rationale,
            "features": self.features,
            "timestamp": self.timestamp.isoformat(),
        }

    def __repr__(self) -> str:
        return (
            f"Signal({self.ticker} {self.direction} via {self.strategy}, "
            f"entry={self.entry_price:.2f}, stop={self.stop_price:.2f}, "
            f"size={self.position_size}, conf={self.confidence:.2f})"
        )


class BaseStrategy(ABC):
    """Abstract base class for all Atlas trading strategies.

    Subclasses must implement:
        - generate_signals(): Scan data and produce entry signals.
        - check_exits(): Evaluate open positions for exit conditions.

    Args:
        config: Full configuration dictionary (from get_active_config()).
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.risk_config = config.get("risk", {})
        self.fees_config = config.get("fees", {})
        self._logger = logging.getLogger(f"{__name__}.{self.name}")
        self._precomputed = False

    @property
    def name(self) -> str:
        """Return the strategy name. Defaults to class name."""
        return self.__class__.__name__

    def precompute(self, data: Dict[str, pd.DataFrame]) -> None:
        """Pre-compute indicators as DataFrame columns. Override in subclasses.

        Called once before backtesting. Adds indicator columns to each ticker's
        DataFrame so generate_signals/check_exits can read them instead of
        recomputing every day. Column names MUST be prefixed with strategy
        abbreviation (e.g., '_mr_rsi', '_tf_fast_ma') to avoid collisions.

        After adding columns, set self._precomputed = True.
        """
        pass

    @abstractmethod
    def generate_signals(
        self,
        data: Dict[str, pd.DataFrame],
        equity: float,
        existing_positions: List[Dict[str, Any]],
    ) -> List[Signal]:
        """Generate entry signals by scanning price data.

        Args:
            data: Dict mapping ticker -> OHLCV DataFrame.
                  Each DataFrame has columns: open, high, low, close,
                  adj_close, volume, ticker. Index is DatetimeIndex.
            equity: Current account equity in AUD.
            existing_positions: List of dicts describing open positions.
                  Each dict has at minimum: ticker, strategy, entry_price,
                  shares, entry_date.

        Returns:
            List of Signal objects for new entries.
        """
        ...

    @abstractmethod
    def check_exits(
        self,
        data: Dict[str, pd.DataFrame],
        positions: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Check open positions for exit conditions.

        Args:
            data: Dict mapping ticker -> OHLCV DataFrame.
            positions: List of dicts describing open positions.
                  Each dict has at minimum: ticker, strategy, entry_price,
                  shares, entry_date, stop_price.

        Returns:
            List of exit recommendation dicts, each containing:
                - ticker: str
                - reason: str (e.g., 'stop_hit', 'trailing_stop', 'time_exit',
                          'take_profit', 'signal_exit')
                - exit_price: float (suggested exit price)
                - details: str (human-readable explanation)
        """
        ...

    def _get_held_tickers(self, existing_positions: List[Dict[str, Any]]) -> set:
        """Extract set of tickers currently held."""
        return {p["ticker"] for p in existing_positions if p.get("ticker")}

    def _count_positions(self, existing_positions: List[Dict[str, Any]]) -> int:
        """Count total open positions."""
        return len(existing_positions)

    def _count_sector_positions(
        self, existing_positions: List[Dict[str, Any]], sector: str
    ) -> int:
        """Count open positions in a given sector."""
        return sum(
            1 for p in existing_positions
            if str(p.get("sector", "")).lower() == str(sector).lower()
        )

    def _can_open_position(
        self, existing_positions: List[Dict[str, Any]], sector: str = ""
    ) -> bool:
        """Check if risk limits allow opening a new position."""
        max_positions = self.risk_config.get("max_open_positions", 5)
        max_sector = self.risk_config.get("max_sector_concentration", 2)

        if self._count_positions(existing_positions) >= max_positions:
            return False
        if sector and isinstance(sector, str) and self._count_sector_positions(existing_positions, sector) >= max_sector:
            return False
        return True

    def _has_sufficient_data(self, df: pd.DataFrame, min_rows: int) -> bool:
        """Check if DataFrame has enough rows for indicator calculation."""
        if df is None or df.empty:
            return False
        return len(df) >= min_rows
