"""
tests/test_audit_f13_dashboard_data_absent.py
===============================================
Regression tests for audit finding F-13: legacy dashboard-data.json.

Before the fix:
  - /root/atlas/dashboard/data/dashboard-data.json (101 KB) was present on disk.
  - It was modified at 10:56 AEST on audit day despite generate_data.py being retired.
  - Legacy fallback in static_serve.py served it, though React no longer consumed it.
  - agent.html was also present at the root (unused legacy file).

Fix (commit 95533e20, 2026-05-11):
  - `git rm dashboard/data/dashboard-data.json` — removed from FS and git history.
  - `git rm agent.html` — removed from FS and git history.
  - .gitignore already contained `dashboard/data/` (covered by existing entries).

These tests guard against:
  1. The file being accidentally re-created (generate_data.py, backup restore, etc.).
  2. The file being re-committed to git (which would be a larger problem).
  3. .gitignore coverage being removed (allowing accidental future commits).
  4. agent.html being re-created at the project root.

Audit ref: F-13.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent

_DASHBOARD_DATA_FILE = PROJECT_ROOT / "dashboard" / "data" / "dashboard-data.json"
_AGENT_HTML_FILE = PROJECT_ROOT / "agent.html"
_GITIGNORE_FILE = PROJECT_ROOT / ".gitignore"


# ── Test 1: legacy file does not exist on filesystem ─────────────────────────

def test_dashboard_data_json_not_on_filesystem() -> None:
    """F-13: dashboard/data/dashboard-data.json must not exist on disk.

    The file was present at 101 KB on audit day.  After 'git rm', it must be
    absent.  If it reappears (re-generated by generate_data.py or restored
    from backup), this test will catch it.
    """
    assert not _DASHBOARD_DATA_FILE.exists(), (
        f"F-13 regression: {_DASHBOARD_DATA_FILE} exists on the filesystem. "
        f"Size: {_DASHBOARD_DATA_FILE.stat().st_size if _DASHBOARD_DATA_FILE.exists() else 'n/a'} bytes. "
        f"This file was removed by commit 95533e20 (2026-05-11). "
        f"Possible causes: generate_data.py ran, backup restored, deploy script re-created it."
    )


# ── Test 2: file is not git-tracked ───────────────────────────────────────────

def test_dashboard_data_json_not_git_tracked() -> None:
    """F-13: dashboard/data/dashboard-data.json must not be tracked by git.

    'git ls-files' returns the path only if it is tracked.  Empty output is
    the expected post-fix state.
    """
    result = subprocess.run(
        ["git", "ls-files", "dashboard/data/dashboard-data.json"],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=15,
    )
    tracked = result.stdout.strip()
    assert tracked == "", (
        f"F-13 regression: 'git ls-files' returned '{tracked}' — the file is "
        f"tracked in git again. It was removed from git history by commit 95533e20. "
        f"Run 'git rm dashboard/data/dashboard-data.json' and commit to fix."
    )


# ── Test 3: .gitignore covers dashboard/data/ ─────────────────────────────────

def test_gitignore_covers_dashboard_data_dir() -> None:
    """F-13: .gitignore must include a rule covering dashboard/data/.

    Without the .gitignore entry, a future accidental generate_data.py run
    could silently re-commit a fresh dashboard-data.json to git.

    The .gitignore entry was present before the fix but is verified here to
    guard against it being accidentally pruned.
    """
    if not _GITIGNORE_FILE.exists():
        pytest.skip(f".gitignore not found at {_GITIGNORE_FILE}")

    content = _GITIGNORE_FILE.read_text()

    # Accept either the exact directory form or a glob that covers it
    covers = (
        "dashboard/data/" in content
        or "dashboard/data/*" in content
        or "dashboard/data/**" in content
    )
    assert covers, (
        f"F-13 regression: .gitignore does not contain 'dashboard/data/' (or equivalent). "
        f"Without this entry, a future dashboard-data.json write could be accidentally "
        f"committed to git. Add 'dashboard/data/' to .gitignore."
    )


# ── Test 4: agent.html removed from project root ──────────────────────────────

def test_agent_html_removed() -> None:
    """F-13: agent.html must not exist at the project root.

    The file was a legacy artifact removed by commit 95533e20 alongside
    dashboard-data.json.  If it reappears (deploy restore, branch merge), this
    test will catch it.

    Note: dashboard/data/agent.html is gitignored and unrelated to this check.
    The test specifically checks /root/atlas/agent.html (project root).
    """
    assert not _AGENT_HTML_FILE.exists(), (
        f"F-13 regression: {_AGENT_HTML_FILE} exists at the project root. "
        f"This file was removed by commit 95533e20 (2026-05-11). "
        f"Run 'git rm agent.html' if it was accidentally re-committed."
    )
