/**
 * Guard extension generator for swarm agents.
 *
 * Deploys a .pi/extensions/swarm-guard.ts into each agent's worktree
 * (or the project root for in-place agents) that enforces capability
 * constraints:
 *
 *   - scout/reviewer: read-only (blocks write, edit, bash writes)
 *   - builder: path-boundary + scope/allowlist enforcement
 *   - planner: read-only
 *
 * V2: Directory-based scope system. When `scope` is passed to deployGuard,
 * the generated extension uses isPathAllowed() to enforce directory ownership
 * instead of exact-file matching. A git pre-commit hook is also deployed in
 * builder worktrees as a second line of defense.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { AgentCapability, BuilderScope } from "./types.js";

const READ_ONLY_CAPABILITIES: Set<AgentCapability> = new Set(["scout", "reviewer", "planner"]);

// ── Guard source generator ───────────────────────────────────────────

function generateGuardSource(
  agentName: string,
  capability: AgentCapability,
  worktreePath: string,
  allowedFiles?: string[],
  scope?: BuilderScope,
): string {
  const isReadOnly = READ_ONLY_CAPABILITIES.has(capability);
  const hasAllowlist = !isReadOnly && allowedFiles && allowedFiles.length > 0;
  const hasScope = !isReadOnly && scope !== undefined;
  const allowlistJSON = hasAllowlist ? JSON.stringify(allowedFiles) : "[]";
  const scopeJSON = hasScope ? JSON.stringify(scope) : "null";

  return `// .pi/extensions/swarm-guard.ts
// Generated by pi-swarm — do not edit manually.
// Agent: ${agentName} | Capability: ${capability}
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const AGENT_NAME = "${agentName}";
const CAPABILITY = "${capability}";
const WORKTREE_PATH = "${worktreePath}";
const IS_READ_ONLY = ${isReadOnly};
const ALLOWED_FILES: string[] = ${allowlistJSON};
const HAS_ALLOWLIST = ${hasAllowlist ?? false};
const SCOPE: { ownedDirs: string[]; extraFiles?: string[]; newFilePatterns?: string[] } | null = ${scopeJSON};
const HAS_SCOPE = ${hasScope};

const WRITE_TOOLS = new Set(["write", "edit", "Write", "Edit"]);

// Swarm tools are forbidden inside agent sessions — prevents recursive swarm launches
const BLOCKED_TOOLS = new Set([
  "swarm", "swarm_plan", "swarm_merge", "swarm_status", "swarm_cleanup",
]);

const DANGEROUS_BASH = [
  /\\bgit\\s+push\\b/,
  /\\bgit\\s+reset\\s+--hard/,
  /\\bgit\\s+checkout\\s+-b\\s+(?!swarm\\/)/,
  /\\bgit\\s+branch\\s+-[dD]\\b/,
  /\\brm\\s+-rf\\s+\\//,
];

// Expanded list of file-modifying bash patterns
const FILE_MODIFYING_BASH = [
  /\\bsed\\s+-i/,
  /\\bsed\\s+--in-place/,
  /echo\\s+.*>/,
  /printf\\s+.*>/,
  /cat\\s+.*>/,
  /\\btee\\s/,
  /\\bmv\\s/,
  /\\bcp\\s/,
  /\\brm\\s/,
  /\\bmkdir\\s/,
  /\\bchmod\\s/,
  /\\bchown\\s/,
  /\\btouch\\s/,
  /\\binstall\\s+-[A-Za-z]*m/,
  /\\bpatch\\s/,
  />>/,
  />[^&=]/,
];

const SAFE_BASH_PREFIXES = [
  "git status", "git diff", "git log", "git show", "git branch",
  "git add", "git commit", "git checkout", "git merge",
  "ls", "cat", "head", "tail", "wc", "find", "grep", "rg",
  "echo ", "pwd", "which", "env", "date", "whoami",
  "npm test", "npm run", "npx ", "bun test", "bun run",
  "python -m pytest", "python3 -m pytest",
  "cargo test", "go test", "make test",
  "tsc", "tsc --noEmit",
];

/**
 * Convert a simple glob pattern to a regex string.
 * - ** matches any sequence of characters including / (including zero chars)
 * - **\/ matches an optional path prefix (zero or more segments + slash)
 * - *  matches any sequence of characters except /
 */
function simpleGlobMatch(relPath: string, pattern: string): boolean {
  var re = "";
  var i = 0;
  var specialChars = ".+?^\${}()|[]\\\\";
  while (i < pattern.length) {
    var c = pattern[i];
    if (c === "*" && i + 1 < pattern.length && pattern[i + 1] === "*") {
      // Double-star: check if followed by /
      if (i + 2 < pattern.length && pattern[i + 2] === "/") {
        re += "(.*/)?";  // optional: any path prefix including trailing slash
        i += 3;          // consume **/ together
      } else {
        re += ".*";
        i += 2;
      }
    } else if (c === "*") {
      re += "[^/]*";
      i++;
    } else if (specialChars.indexOf(c) !== -1) {
      re += "\\\\" + c;
      i++;
    } else {
      re += c;
      i++;
    }
  }
  try {
    return new RegExp("^" + re + "$").test(relPath);
  } catch {
    return false;
  }
}

/**
 * Check whether a relative path is allowed by the scope definition.
 */
function isPathAllowed(
  relPath: string,
  scope: { ownedDirs: string[]; extraFiles?: string[]; newFilePatterns?: string[] },
): boolean {
  // Always allow .pi-swarm/ coordination files
  if (relPath.startsWith(".pi-swarm/")) return true;
  // Check owned directories: exact dir match or starts with dir/
  for (var i = 0; i < scope.ownedDirs.length; i++) {
    var dir = scope.ownedDirs[i];
    var prefix = dir.endsWith("/") ? dir : dir + "/";
    if (relPath === dir || relPath === prefix.slice(0, -1) || relPath.startsWith(prefix)) return true;
  }
  // Check extra files (exact match)
  if (scope.extraFiles) {
    for (var j = 0; j < scope.extraFiles.length; j++) {
      if (relPath === scope.extraFiles[j]) return true;
    }
  }
  // Check new file patterns (simple glob)
  if (scope.newFilePatterns) {
    for (var k = 0; k < scope.newFilePatterns.length; k++) {
      if (simpleGlobMatch(relPath, scope.newFilePatterns[k])) return true;
    }
  }
  return false;
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event) => {
    // 0. Block swarm tools — agents must not spawn nested swarms
    if (BLOCKED_TOOLS.has(event.toolName)) {
      return {
        block: true,
        reason: \`Recursive swarm call blocked: \${event.toolName} is not allowed inside a swarm agent. Complete your task directly using code tools.\`,
      };
    }

    // 1. Block dangerous git operations (all agents)
    if (event.toolName === "bash") {
      const cmd = String((event.input as any)?.command ?? "");
      for (const pattern of DANGEROUS_BASH) {
        if (pattern.test(cmd)) {
          return {
            block: true,
            reason: \`Blocked: \${cmd.slice(0, 60)}... — dangerous git operation not allowed in swarm agents\`,
          };
        }
      }
    }

    // 2. Read-only enforcement (scouts, reviewers, planners)
    if (IS_READ_ONLY) {
      if (WRITE_TOOLS.has(event.toolName)) {
        return {
          block: true,
          reason: \`\${CAPABILITY} agents are read-only — \${event.toolName} is not allowed. Report your findings instead.\`,
        };
      }
      if (event.toolName === "bash") {
        const cmd = String((event.input as any)?.command ?? "");
        const trimmed = cmd.trimStart();
        if (SAFE_BASH_PREFIXES.some((p) => trimmed.startsWith(p))) return;
        for (const pattern of FILE_MODIFYING_BASH) {
          if (pattern.test(cmd)) {
            return {
              block: true,
              reason: \`\${CAPABILITY} agents are read-only — this bash command modifies files\`,
            };
          }
        }
      }
    }

    // 3. Path boundary for builders: write/edit must stay in worktree
    if (!IS_READ_ONLY && WRITE_TOOLS.has(event.toolName)) {
      const filePath = String(
        (event.input as any)?.path ?? (event.input as any)?.file_path ?? "",
      );
      if (filePath && !filePath.startsWith(WORKTREE_PATH + "/") && filePath !== WORKTREE_PATH) {
        if (filePath.startsWith("/")) {
          return {
            block: true,
            reason: "Path boundary: file is outside your assigned worktree. All writes must target files within your worktree.",
          };
        }
      }
    }

    // 3b. Scope / allowlist enforcement for builders
    if (!IS_READ_ONLY && WRITE_TOOLS.has(event.toolName)) {
      const filePath = String(
        (event.input as any)?.path ?? (event.input as any)?.file_path ?? "",
      );
      if (filePath) {
        // Normalize to relative path
        let relPath = filePath;
        if (relPath.startsWith(WORKTREE_PATH + "/")) {
          relPath = relPath.slice(WORKTREE_PATH.length + 1);
        }
        if (relPath.startsWith("./")) relPath = relPath.slice(2);

        if (HAS_SCOPE && SCOPE) {
          // Directory-based scope enforcement
          if (!isPathAllowed(relPath, SCOPE)) {
            return {
              block: true,
              reason: \`Scope violation: \${relPath} is outside your owned directories [\${SCOPE.ownedDirs.join(", ")}]. Only modify files within your assigned scope.\`,
            };
          }
        } else if (HAS_ALLOWLIST) {
          // Fallback: exact allowlist check (backward compatibility)
          const allowed = ALLOWED_FILES.some((f) => {
            if (relPath === f) return true;
            if (relPath.endsWith(".pyc") || relPath.endsWith(".pyo")) return true;
            return false;
          });
          if (!allowed) {
            return {
              block: true,
              reason: \`File ownership violation: \${relPath} is not in your assigned files [\${ALLOWED_FILES.join(", ")}]. Only modify files you own.\`,
            };
          }
        }
      }
    }

    // 4. Path boundary for builders (bash file-modifying commands)
    if (!IS_READ_ONLY && event.toolName === "bash") {
      const cmd = String((event.input as any)?.command ?? "");

      if (FILE_MODIFYING_BASH.some((re) => re.test(cmd))) {
        // Extract absolute paths from the command and check if they're in-worktree
        const tokens = cmd.split(/\\s+/);
        const absPaths = tokens
          .filter((t) => t.startsWith("/"))
          .map((t) => t.replace(/[";>'|]*$/, ""));
        for (const p of absPaths) {
          if (
            !p.startsWith("/dev/") &&
            !p.startsWith("/tmp/") &&
            !p.startsWith(WORKTREE_PATH + "/") &&
            p !== WORKTREE_PATH
          ) {
            return {
              block: true,
              reason: "Path boundary: bash command targets a path outside your worktree.",
            };
          }
        }

        // Scope catch-all: warn if a command references paths that look outside scope.
        // This is advisory — the git pre-commit hook is the real enforcement.
        if (HAS_SCOPE && SCOPE && absPaths.length === 0) {
          // Command uses relative paths or no paths — rely on pre-commit hook.
          // Do not block; just allow it to proceed.
        }
      }
    }

    // Default: allow
  });
}
`;
}

// ── Pre-commit hook generator ────────────────────────────────────────

function generatePreCommitHook(scope: BuilderScope): string {
  // Shell-quote the arrays for embedding in the hook script
  const ownedDirs = scope.ownedDirs
    .map((d) => (d.endsWith("/") ? d : d + "/"))
    .join(" ");
  const extraFiles = (scope.extraFiles ?? []).join(" ");
  const newFilePatterns = (scope.newFilePatterns ?? []).join(" ");

  return `#!/bin/bash
# Auto-generated by pi-swarm guard — do not edit manually.
# Enforces builder scope at commit time. Blocks commits with out-of-scope files.

OWNED_DIRS="${ownedDirs}"
EXTRA_FILES="${extraFiles}"
NEW_FILE_PATTERNS="${newFilePatterns}"
BLOCKED=()

for file in $(git diff --cached --name-only); do
  allowed=false

  # Always allow .pi-swarm/ coordination files
  [[ "$file" == .pi-swarm/* ]] && allowed=true

  # Check owned directories
  for dir in $OWNED_DIRS; do
    [[ "$file" == "$dir" || "$file" == "\${dir}"* ]] && allowed=true
  done

  # Check extra files (exact match)
  for ef in $EXTRA_FILES; do
    [[ "$file" == "$ef" ]] && allowed=true
  done

  # Check new file patterns (bash glob matching)
  for pat in $NEW_FILE_PATTERNS; do
    # shellcheck disable=SC2254
    [[ "$file" == $pat ]] && allowed=true
  done

  if ! $allowed; then
    BLOCKED+=("$file")
    echo "⚠️  SCOPE VIOLATION: $file is outside your owned scope. Unstaging..."
    git reset HEAD -- "$file" 2>/dev/null
  fi
done

if [ \${#BLOCKED[@]} -gt 0 ]; then
  echo ""
  echo "The following files were unstaged due to scope violations:"
  for f in "\${BLOCKED[@]}"; do
    echo "  ✗ $f"
  done
  echo ""
  echo "Owned dirs : $OWNED_DIRS"
  echo "Extra files: $EXTRA_FILES"
  echo ""
  echo "To override (emergency only): git commit --no-verify"
  exit 1
fi
`;
}

// ── Worktree hooks directory resolver ───────────────────────────────

/**
 * Resolve the actual hooks directory for a worktree.
 * Git worktrees use a .git FILE (not directory), pointing to the real gitdir.
 */
function resolveHooksDir(targetDir: string): string {
  const gitEntry = path.join(targetDir, ".git");
  if (!fs.existsSync(gitEntry)) return path.join(targetDir, ".git", "hooks");

  const stat = fs.statSync(gitEntry);
  if (stat.isDirectory()) {
    return path.join(gitEntry, "hooks");
  }

  // It's a file — read the gitdir pointer
  const content = fs.readFileSync(gitEntry, "utf-8").trim();
  const match = content.match(/^gitdir:\s*(.+)$/);
  if (!match) return path.join(targetDir, ".git", "hooks");

  const gitdir = match[1].startsWith("/")
    ? match[1]
    : path.join(targetDir, match[1]);
  return path.join(gitdir, "hooks");
}

// ── Public API ───────────────────────────────────────────────────────

/**
 * Deploy guard extension into a worktree (or project root for in-place agents).
 *
 * @param agentName   Human-readable agent identifier
 * @param capability  Agent role: scout | builder | reviewer | planner
 * @param targetDir   Absolute path to the worktree or project root
 * @param allowedFiles  Exact file list for legacy allowlist enforcement (backward compat)
 * @param scope         Directory-based scope for builders (preferred over allowedFiles)
 */
export function deployGuard(
  agentName: string,
  capability: AgentCapability,
  targetDir: string,
  allowedFiles?: string[],
  scope?: BuilderScope,
): void {
  const extDir = path.join(targetDir, ".pi", "extensions");
  fs.mkdirSync(extDir, { recursive: true });

  const guardSource = generateGuardSource(agentName, capability, targetDir, allowedFiles, scope);
  fs.writeFileSync(path.join(extDir, "swarm-guard.ts"), guardSource);

  // Deploy git pre-commit hook for builders that have a scope
  if (scope && capability === "builder") {
    try {
      const hooksDir = resolveHooksDir(targetDir);
      fs.mkdirSync(hooksDir, { recursive: true });
      const hookPath = path.join(hooksDir, "pre-commit");
      const hookContent = generatePreCommitHook(scope);
      fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
    } catch {
      // Non-fatal: pre-commit hook is advisory, guard extension is the primary enforcement
    }
  }

  // Write settings.json to enable the extensions directory
  const piDir = path.join(targetDir, ".pi");
  const settingsPath = path.join(piDir, "settings.json");

  let settings: Record<string, unknown> = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    } catch {
      // Overwrite corrupt settings
    }
  }

  if (!settings.extensions) settings.extensions = [];
  if (!(settings.extensions as string[]).includes("./extensions")) {
    (settings.extensions as string[]).push("./extensions");
  }

  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n");
}

/**
 * Remove guard extension (and pre-commit hook if ours) from a directory.
 */
export function removeGuard(targetDir: string): void {
  // Remove guard extension
  const guardPath = path.join(targetDir, ".pi", "extensions", "swarm-guard.ts");
  try {
    fs.unlinkSync(guardPath);
  } catch {
    // Fine if it doesn't exist
  }

  // Remove pre-commit hook only if it was generated by us
  try {
    const hooksDir = resolveHooksDir(targetDir);
    const hookPath = path.join(hooksDir, "pre-commit");
    if (fs.existsSync(hookPath)) {
      const content = fs.readFileSync(hookPath, "utf-8");
      if (content.includes("Auto-generated by pi-swarm guard")) {
        fs.unlinkSync(hookPath);
      }
    }
  } catch {
    // Non-fatal
  }
}
